<a href="https://colab.research.google.com/github/SHOBHEY/AVINASH/blob/main/Q2_Row_Echelon_Form_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Q2. Row Echelon Form:**

In [1]:
import numpy as np

# To Set the random seed using the last two digits of my roll number i.e. 09
np.random.seed(9)

A = np.random.randint(0, 10, size=(5, 5))

def reduce_to_row_echelon_form(matrix):
    num_rows, num_cols = matrix.shape
    lead = 0
    for r in range(num_rows):
        if lead >= num_cols:
            break
        i = r
        while matrix[i, lead] == 0:
            i += 1
            if i == num_rows:
                i = r
                lead += 1
                if num_cols == lead:
                    return matrix
        matrix[[i, r]] = matrix[[r, i]]
        if matrix[r, lead] != 0:
            matrix[r] = matrix[r] / matrix[r, lead]
        for i in range(num_rows):
            if i != r:
                matrix[i] = matrix[i] - matrix[i, lead] * matrix[r]
        lead += 1
    return matrix

row_echelon_A = reduce_to_row_echelon_form(A)
print("Original matrix A:")
print(A)
print("\nRow Echelon Form of matrix A:")
print(row_echelon_A)


Original matrix A:
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]

Row Echelon Form of matrix A:
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
