<a href="https://colab.research.google.com/github/SHOBHEY/AVINASH/blob/main/Q3_Singular_Value_Decomposition_(SVD)_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Q3. Singular Value Decomposition (SVD):**

In [1]:
import numpy as np

np.random.seed(22)
A = np.random.randint(0, 10, size=(5, 5))

# Perform Singular Value Decomposition (SVD) on matrix A
U, Sigma, Vt = np.linalg.svd(A)
print("Matrix U:")
print(U)
print("\nMatrix Sigma (Diagonal matrix):")
print(np.diag(Sigma))
print("\nMatrix Vt (Transpose of V):")
print(Vt)
A_reconstructed = np.dot(U, np.dot(np.diag(Sigma), Vt))
print("\nIs A equal to the product of U, Sigma, and Vt? ", np.allclose(A, A_reconstructed))

# Rank 2 approximation of matrix A
rank_2_approximation = np.dot(U[:, :2], np.dot(np.diag(Sigma[:2]), Vt[:2, :]))
print("\nRank 2 approximation of matrix A:")
print(rank_2_approximation)

# Rank 3 approximation of matrix A
rank_3_approximation = np.dot(U[:, :3], np.dot(np.diag(Sigma[:3]), Vt[:3, :]))
print("\nRank 3 approximation of matrix A:")
print(rank_3_approximation)


Matrix U:
[[-0.34966012  0.41846152 -0.11715402 -0.39622406  0.72932105]
 [-0.43353269 -0.41989712  0.28603192  0.61798002  0.41475566]
 [-0.62245303  0.49217946 -0.25866209  0.31889741 -0.44912133]
 [-0.39627638 -0.0739169   0.72897936 -0.47278946 -0.28733349]
 [-0.38118822 -0.63314456 -0.55330253 -0.36862144 -0.1086188 ]]

Matrix Sigma (Diagonal matrix):
[[24.70467411  0.          0.          0.          0.        ]
 [ 0.          9.70171042  0.          0.          0.        ]
 [ 0.          0.          5.3650222   0.          0.        ]
 [ 0.          0.          0.          2.36583297  0.        ]
 [ 0.          0.          0.          0.          1.08409568]]

Matrix Vt (Transpose of V):
[[-0.52137989 -0.47596069 -0.39381079 -0.43194117 -0.3999554 ]
 [ 0.23561627 -0.07513501 -0.86260941  0.24496765  0.36706343]
 [ 0.80887963 -0.15098564 -0.05458954 -0.34564554 -0.44773455]
 [ 0.05368171 -0.61558456  0.1576122   0.72095423 -0.27121453]
 [ 0.12441868 -0.60504144  0.27017855 -0.337